apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: k8s-demo
build:
  artifacts:
  - image: k8s-demo-frontend
    context: ./app/frontend
    docker:
      dockerfile: Dockerfile
  - image: k8s-demo-api
    context: ./app/api
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
    flags:
      global:
        - --namespace=k8s-demo
portForward:
- resourceType: service
  resourceName: k8s-demo-frontend-service
  port: 3000
  localPort: 3000
- resourceType: service
  resourceName: k8s-demo-api-service
  port: 8080
  localPort: 8080
profiles:
- name: dev
  build:
    local:
      push: false
  deploy:
    kubectl:
      manifests:
        - k8s/*.yaml
      flags:
        global:
          - --namespace=k8s-demo
- name: prod
  build:
    googleCloudBuild:
      projectId: your-gcp-project-id
  deploy:
    kubectl:
      manifests:
        - k8s/*.yaml
      flags:
        global:
          - --namespace=k8s-demo
