apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8s-demo
build:
  artifacts:
  - image: k8s-demo-frontend
    context: ./app/frontend
    docker:
      dockerfile: Dockerfile
  - image: k8s-demo-api
    context: ./app/api
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
    flags:
      global:
        - --namespace=k8s-demo