apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-demo-ingress
  namespace: k8s-demo
  labels:
    app.kubernetes.io/name: k8s-demo-ingress
    app.kubernetes.io/part-of: k8s-demo
  annotations:
    # For cloud providers, you might need specific annotations
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: "nginx"
    # For local development with kind/minikube
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost  # Change this to your domain for production
    http:
      paths:
      # Frontend routes
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-demo-frontend-service
            port:
              number: 3000
      # Backend API routes
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: k8s-demo-api-service
            port:
              number: 8080
  # For production, you might want to add TLS
  # tls:
  # - hosts:
  #   - your-domain.com
  #   secretName: k8s-demo-tls
