apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-demo-ingress
  namespace: k8s-demo
  labels:
    app.kubernetes.io/name: k8s-demo-ingress
    app.kubernetes.io/part-of: k8s-demo
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      # Backend API routes - must come first for proper matching
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: k8s-demo-api-service
            port:
              number: 8080
      # Frontend routes - catch all other requests
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-demo-frontend-service
            port:
              number: 3000