apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-api-service
  namespace: k8s-demo
  labels:
    app: k8s-demo-api
    app.kubernetes.io/name: k8s-demo-api
    app.kubernetes.io/part-of: k8s-demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-demo-api
